[google_service_account]
type = "service_account"
project_id = "gen-lang-client-0709660306"
private_key_id = "d66c48c393e4419740dbb56f21d7bf1239ef7431"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCe5ghho+lq6RST
TKca33vGtOsZ+QGHRIJHakJSmwltrs6pFOB2uH7W7s/l5EvOPtI07aJeLV7BD8Kr
uhoIeLQPAXrs9pOC/7M/9gblAKzMlaaLpqp1pWdrTbbTYDXHYugnbVBr8NexrJs1
eDGXtnlTdtsaF3fFSffuIJUzI6U8BZJtojEEl/a+eHOcbDAf3DpAlAODA33JpISJ
QYdy9Q4EvwdUH1v/nfsCUbo2vQYvnrOVoupX5HERA/9CYQF9b9t+bpxR+yLTF4cZ
QepQcg6Ilo83pfxiIozX4Q8WqFm5rEyFf11BigXyoynHYMQyw++//DI1xg3odcTM
GycVfz9bAgMBAAECggEACA8qxakGocGIpZ/xqc9D++QZOIwEo9O5t92P15i9da60
FKdWay8YX9Zk/QgDQEa3aq/S2Gv8rlYaTZN21o8ossokbfhjqvVFJi1YVC0glo/Q
jqy5YJYvFKYwa7Apih9eHwHQXmksx3o1tRSPj15V8QHKQxyFmqARzyYf6yQXsV+S
hAC5fkipBsM4gvKlEQXFJpwV+EQtSGQQQHBdumfKJC63H+jm/cbFZxPxknag+6hZ
XuZ84gu2PcWdJIlo7TPC5SdyV46OiJuiZsyU6IYjjk7fFcZZ4dkLM1k17vJMjPuV
+vK+rHawdQXkYMzaRFbz2NMbVyXBc+GND9dq6AMgIQKBgQDLDuKuOx7K8nnkblr/
un4KMe3Ey+1/YsHuiPCsPpIYPVj77tapLWFBccNGEzAcrBTGG1dUuufpPfT/eqeu
c9IXzab2NXm/B1p4p1TmpgmocncGZ8CJWEuaRuMDZx2n2ALHYYXRwTp+22l+YSxz
6dzFkqcSY6IqtF0DCmVNGEZNRQKBgQDIU7di0ypcNQZRF6S/+o9Pc0plz9+nyubZ
baFm2gHg1TIJCXqwdV/oP26sVDV3C+hsdRGvcwtLo1Huq808WQsef54ZZ0ugPY3/
x1Zk7aOKZ0PHTI0P07QOQwVXJiDCknrGQS9Uuh8XSUIv94Pdl/ssqKNcBwrjYrDd
/b7hvBCUHwKBgCcLs7cBE0i/G4U7WzA1cisPssLW29JU8SmnF3Bnj7wtf8DiClD5
suvcrkn5QpUg2dXGSCK41gNZsJS3xyqahtmg5+wMGF8NUO5GbuLzJoRHjm+i37kJ
S3BdFSYAXAl8Vfx02kCdQVxHYJ+2m8+mNpefPZUhp3tCt2fwRc5vToVpAoGBAL4e
5a6+5jb4g/Q2Uj95FsW6j2Ms9ACVCp5T85hfUuUEsSXufyg1XT5X5Ttb+BnxjTZR
rOUsdA3nBH1VQ8UAZRMe3vcRF68OfFPB5XaIKmvSMXtWZZIdw4a9iLX7E6BV0HuT
pc3tjlBVUKGhcN6/vLvXmKJgdK71HRKyHZSzHbDVAoGAGuXfeeJsTJRLexkuTKvr
wlVLOjK4j33L8tF4NXjsvPI7TFXql/LAedsu9TdsruZEvSbNyMgN/U+WaGpdmEGn
YujOeRAjyzB2wvLvtnJiuOq8EzapnQPKJkuNjtom4CgxYtyhvaSnaTXxBEha8DI3
hJONZlO8G/JJVsRX/nsP2K4=
-----END PRIVATE KEY-----"""
client_email = "project-ik-245@gen-lang-client-0709660306.iam.gserviceaccount.com"
client_id = "114163668200477426345"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/project-ik-245%40gen-lang-client-0709660306.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
